### ISSUE TITLE
Seconds on the timetable

### ISSUE THREAD

**Issue by fortepian** [tmaciejewski/ipa#1]
Timetables on infopasazer.intercity.pl are more accurate than those on the other sites of PKP – they include seconds of the time of arrivals. It is a very interesting data to analyze, especially on regional and city trains. I'm not very common with Python (I use C# and C++) so I don't know whether in your database schedules are stored with seconds or not. But if they are stored with seconds, I think seconds could also appear in the frontend website.

**Comment by tmaciejewski** [comment]
Times are kept as `datetime` (see `src/ipa_db_schema.py`) and they actually are saved. The main purpose of this project was to track long-distance trains (intercity), which have greater chances of being late on schedule, than city trains that goes every half an hour. And for intercity trains data on InfoPasażer is accurate only to minutes with seconds as ":00", that is why I decided not to show it.

**Comment by fortepian** [comment]
Is it possible to get those accurate times from database in some other way than from the website?

**Comment by tmaciejewski** [comment]
You can use REST API, `/api/trains/{train_number}`, eg.

http://ipa.lovethosetrains.com/api/trains/96904/5

**Comment by fortepian** [comment]
Great! It's all I need. It’s funny that I was now analyzing those Kościerzyna–Gdynia trains ;)
