### ISSUE TITLE
Brak niektórych pociągów i aktualizacji

### ISSUE THREAD

**Issue by TeslaX93** [tmaciejewski/ipa#3]
Nie wiem czy to jest odpowiednie miejsce do tego - ale czy brak aktualizacji na przykład pociągu Gwarek od nowego rozkładu jazdy, albo np. brak pociągu KW 77212 jest czymś szczególnym uzasadniony?

**Comment by tmaciejewski** [comment]
Nie jest niczym uzasadniony. Generalnie jeśli pociąg jest widoczny w InfoPasażerze (sprawdzanych jest kilkanaście głównych stacji), to powinien być też widoczny. Był jakiś problem z dodawaniem niektórych pociągów do bazy, powinno już być OK. Dzięki za zgłoszenie.
