### ISSUE TITLE
Historical data has stopped being index?

### ISSUE THREAD

**Issue by krzakx** [tmaciejewski/ipa#4]
Hi!
I do see that on web portal ipa.lovethosetrains.com/ last data is from 8th May, has something been change on data source provider?

**Comment by sthokrotka** [comment]
The service providing the data (https://infopasazer.intercity.pl/) was unfortunately shut down on 8th May 2023.

**Comment by tmaciejewski** [comment]
Yes, @ahts97 is right, and it means this project has ended.
